name: flutter_gherkin
description: A Gherkin / Cucumber parser and test runner for Dart and Flutter
version: 3.0.0-rc.17
homepage: https://github.com/jonsamwell/flutter_gherkin

environment:
  sdk: "^3.4.1"
  flutter: 3.22.3

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  collection: ^1.18.0
  gherkin: ^3.1.0
  source_gen: ^1.5.0
  build: ^2.4.1
  glob: ^2.1.2

dev_dependencies:
  meta: '>=1.15.0'
  pedantic: ^1.11.1
  build_config: ^1.1.1
  flutter_lints: ^4.0.0

dependency_overrides:
  meta: 1.12.0

flutter:
